// Generated by gencpp from file firsttry/AddTwoInts.msg
// DO NOT EDIT!


#ifndef FIRSTTRY_MESSAGE_ADDTWOINTS_H
#define FIRSTTRY_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <firsttry/AddTwoIntsRequest.h>
#include <firsttry/AddTwoIntsResponse.h>


namespace firsttry
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace firsttry


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::firsttry::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::firsttry::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::firsttry::AddTwoInts > {
  static const char* value()
  {
    return "firsttry/AddTwoInts";
  }

  static const char* value(const ::firsttry::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::firsttry::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::firsttry::AddTwoInts >
template<>
struct MD5Sum< ::firsttry::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::firsttry::AddTwoInts >::value();
  }
  static const char* value(const ::firsttry::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::firsttry::AddTwoIntsRequest> should match
// service_traits::DataType< ::firsttry::AddTwoInts >
template<>
struct DataType< ::firsttry::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::firsttry::AddTwoInts >::value();
  }
  static const char* value(const ::firsttry::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::firsttry::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::firsttry::AddTwoInts >
template<>
struct MD5Sum< ::firsttry::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::firsttry::AddTwoInts >::value();
  }
  static const char* value(const ::firsttry::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::firsttry::AddTwoIntsResponse> should match
// service_traits::DataType< ::firsttry::AddTwoInts >
template<>
struct DataType< ::firsttry::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::firsttry::AddTwoInts >::value();
  }
  static const char* value(const ::firsttry::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRSTTRY_MESSAGE_ADDTWOINTS_H
