// Generated by gencpp from file firsttry/chatResponse.msg
// DO NOT EDIT!


#ifndef FIRSTTRY_MESSAGE_CHATRESPONSE_H
#define FIRSTTRY_MESSAGE_CHATRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace firsttry
{
template <class ContainerAllocator>
struct chatResponse_
{
  typedef chatResponse_<ContainerAllocator> Type;

  chatResponse_()
    : b()  {
    }
  chatResponse_(const ContainerAllocator& _alloc)
    : b(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::firsttry::chatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::firsttry::chatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct chatResponse_

typedef ::firsttry::chatResponse_<std::allocator<void> > chatResponse;

typedef boost::shared_ptr< ::firsttry::chatResponse > chatResponsePtr;
typedef boost::shared_ptr< ::firsttry::chatResponse const> chatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::firsttry::chatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::firsttry::chatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::firsttry::chatResponse_<ContainerAllocator1> & lhs, const ::firsttry::chatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::firsttry::chatResponse_<ContainerAllocator1> & lhs, const ::firsttry::chatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace firsttry

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::firsttry::chatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::firsttry::chatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::firsttry::chatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::firsttry::chatResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::firsttry::chatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::firsttry::chatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::firsttry::chatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ce4159d4691541e9099927d38b0b65f";
  }

  static const char* value(const ::firsttry::chatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ce4159d4691541eULL;
  static const uint64_t static_value2 = 0x9099927d38b0b65fULL;
};

template<class ContainerAllocator>
struct DataType< ::firsttry::chatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "firsttry/chatResponse";
  }

  static const char* value(const ::firsttry::chatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::firsttry::chatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string b\n"
"\n"
;
  }

  static const char* value(const ::firsttry::chatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::firsttry::chatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct chatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::firsttry::chatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::firsttry::chatResponse_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRSTTRY_MESSAGE_CHATRESPONSE_H
